/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

import { describe, expect, it } from 'vitest'
import { classifyByContent } from './contentRules.ts'
import type { BlobSummary } from './contentReader.ts'

function summary(content: string): BlobSummary {
  return { lines: content.split('\n') }
}

function expectGenerated(path: string, content: string): void {
  expect(classifyByContent(path, summary(content))).toEqual({
    generated: true,
  })
}

function expectNotGenerated(path: string, content: string): void {
  expect(classifyByContent(path, summary(content))).toEqual({})
}

describe('classifyByContent — minified', () => {
  it('flags .js when avg line length > 110', () => {
    const content = 'x'.repeat(500) + '\n' + 'y'.repeat(500)
    expectGenerated('app.js', content)
  })

  it("doesn't flag short .js files", () => {
    expectNotGenerated('src/app.js', 'const a = 1\nconst b = 2\n')
  })

  it("doesn't flag .ts even when long", () => {
    // Minification detection is only for .js/.css per Linguist.
    const content = 'x'.repeat(500) + '\n' + 'y'.repeat(500)
    expectNotGenerated('app.ts', content)
  })
})

describe('classifyByContent — source map references and files', () => {
  it('flags .js with trailing sourceMappingURL comment', () => {
    expectGenerated('bundle.js', 'const x = 1\n//# sourceMappingURL=bundle.js.map\n')
  })

  it('flags .map files by name', () => {
    expectGenerated('bundle.js.map', '{"version":3,"sources":["foo.js"]}')
    expectGenerated('styles.css.map', '{"version":3}')
  })

  it('flags .map files by revision 2 header', () => {
    expectGenerated('foo.map', '{"version":3,"sources":[]}')
  })

  it("doesn't flag random .map files without the header", () => {
    expectNotGenerated('world.map', 'just some map data\n')
  })
})

describe('classifyByContent — compiled CoffeeScript', () => {
  it('flags .js with "// Generated by" comment on the first line', () => {
    expectGenerated('app.js', '// Generated by CoffeeScript 1.12.7\nconst x = 1')
  })

  it('flags via structural pattern + score threshold', () => {
    const lines = [
      '(function() {',
      '  var _fn, _i, _len, _ref, _results;',
      '  var __bind = function() {};',
      '}).call(this);',
      '',
    ]
    expectGenerated('app.js', lines.join('\n'))
  })

  it("doesn't flag structurally-similar non-Coffee code", () => {
    const lines = ['(function() {', '  const x = 1', '}).call(this);', '']
    expectNotGenerated('app.js', lines.join('\n'))
  })
})

describe('classifyByContent — generated .NET docfile', () => {
  it('flags .xml with <doc>/<assembly>/</doc>', () => {
    const content = [
      '<?xml version="1.0"?>',
      '<doc>',
      '  <assembly><name>Foo</name></assembly>',
      '  <members />',
      '</doc>',
      '',
    ].join('\n')
    expectGenerated('Foo.xml', content)
  })
})

describe('classifyByContent — PEG.js parser', () => {
  it('flags .js with PEG.js banner in first 5 lines', () => {
    expectGenerated(
      'parser.js',
      '/*\n * Generated by PEG.js 0.10.0.\n */\nmodule.exports = ...\n',
    )
  })
})

describe('classifyByContent — PostScript', () => {
  it('flags .ps with ImageMagick Creator line', () => {
    expectGenerated(
      'graph.ps',
      '%!PS-Adobe-3.0\n%%Creator: ImageMagick 7.1.0\n%%Title: foo\n',
    )
  })

  it('flags .ps with eexec marker', () => {
    expectGenerated('font.ps', 'currentfile eexec\nAABBCC\n')
  })
})

describe('classifyByContent — protobuf variants', () => {
  it('flags .proto files from go-to-protobuf', () => {
    expectGenerated(
      'foo.proto',
      '// This file was autogenerated by go-to-protobuf. DO NOT EDIT.\nsyntax = "proto3";\n',
    )
  })

  it('flags protoc-generated C++/Java/Python', () => {
    const banner = '// Generated by the protocol buffer compiler.  DO NOT EDIT!\n'
    expectGenerated('foo.pb.cc', banner + 'code;\n')
    expectGenerated('Foo.java', banner + 'class Foo {}\n')
    expectGenerated('foo_pb2.py', banner + 'print(1)\n')
  })

  it('flags protoc-generated JS at line 5', () => {
    const content = [
      '// source: foo.proto',
      '/**',
      ' * @fileoverview',
      ' * @enhanceable',
      ' * @suppress {missingRequire}',
      '// GENERATED CODE -- DO NOT EDIT!',
      'var foo = ...;',
    ].join('\n')
    expectGenerated('foo_pb.js', content)
  })

  it('flags ts-proto .ts on line 0', () => {
    expectGenerated(
      'foo.ts',
      '// Code generated by protoc-gen-ts_proto. DO NOT EDIT.\n// versions:\n//   protoc-gen-ts_proto v1\n// source: hello.proto\n\nexport interface Foo {}\n',
    )
  })
})

describe('classifyByContent — Apache Thrift', () => {
  it('flags files with Thrift banner in first 6 lines', () => {
    const banner = '/**\n * Autogenerated by Thrift Compiler (0.15.0)\n *\n */\n'
    expectGenerated('foo.java', banner + 'class Foo {}\n')
  })
})

describe('classifyByContent — JNI header', () => {
  it('flags JNI-generated headers', () => {
    const content =
      '/* DO NOT EDIT THIS FILE - it is machine generated */\n#include <jni.h>\n/* Header for class com_Example */\n'
    expectGenerated('com_Example.h', content)
  })
})

describe('classifyByContent — VCR cassette', () => {
  it('flags .yml with VCR tail', () => {
    const content = ['http_interactions: []', 'recorded_with: VCR 6.0.0', ''].join('\n')
    expectGenerated('cassette.yml', content)
  })
})

describe('classifyByContent — Cython', () => {
  it('flags .c generated by Cython', () => {
    expectGenerated(
      'foo.c',
      '/* Generated by Cython 0.29.21 */\n#define PY_SSIZE_T_CLEAN\n',
    )
  })
})

describe('classifyByContent — Unity3D / Racc / JFlex / GrammarKit / roxygen2', () => {
  it('Unity3D .meta', () => {
    expectGenerated('foo.meta', 'fileFormatVersion: 2\nguid: abc\n')
  })
  it('Racc .rb', () => {
    expectGenerated(
      'parser.rb',
      '# frozen_string_literal: true\nrequire "racc"\n# This file is automatically generated by Racc 1.6.0\nmodule Parser\nend\n',
    )
  })
  it('JFlex .java', () => {
    expectGenerated(
      'Lexer.java',
      '/* The following code was generated by JFlex 1.8.2 */\npublic class Lexer {}\n',
    )
  })
  it('GrammarKit .java', () => {
    expectGenerated(
      'Parser.java',
      '// This is a generated file. Not intended for manual editing.\npublic class Parser {}\n',
    )
  })
  it('roxygen2 .Rd', () => {
    expectGenerated(
      'foo.Rd',
      '% Generated by roxygen2: do not edit by hand\n% Please edit documentation in R/foo.R\n',
    )
  })
})

describe('classifyByContent — Go', () => {
  it('flags .go with "Code generated ..." comment', () => {
    expectGenerated(
      'zz_generated.go',
      '// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n',
    )
  })
})

describe('classifyByContent — gRPC C++', () => {
  it('flags generated gRPC C++ headers', () => {
    expectGenerated(
      'foo.grpc.pb.h',
      '// Generated by the gRPC C++ plugin.\n// If you make any local changes they will be lost\n',
    )
  })
})

describe('classifyByContent — Dart', () => {
  it('flags Dart with "GENERATED CODE - DO NOT MODIFY"', () => {
    expectGenerated(
      'foo.g.dart',
      'part of foo;\n// GENERATED CODE - DO NOT MODIFY\n\npart foo {}\n',
    )
  })
})

describe('classifyByContent — Haxe output', () => {
  it('flags Haxe output JS', () => {
    expectGenerated('foo.js', '// Generated by Haxe 4.2.5\n(function() {})\n')
  })
})

describe('classifyByContent — generated HTML', () => {
  it('flags pkgdown-generated HTML', () => {
    expectGenerated(
      'index.html',
      '<!DOCTYPE html>\n<!-- Generated by pkgdown: do not edit by hand -->\n<html>\n',
    )
  })
  it('flags Doxygen-generated HTML', () => {
    const content =
      '<!DOCTYPE html>\n<html>\n<head>\n<!-- Generated by Doxygen 1.9.1 -->\n</head>\n'
    expectGenerated('class.html', content)
  })
  it('flags groff-generated HTML via <meta name="generator">', () => {
    const content =
      '<html>\n<head>\n<meta name="generator" content="groff -Thtml" />\n</head>\n'
    expectGenerated('man.html', content)
  })
})

describe('classifyByContent — Sorbet RBI from Tapioca', () => {
  it('flags typed:-prefixed RBI with Tapioca banner', () => {
    const content = [
      '# typed: true',
      '',
      '# DO NOT EDIT MANUALLY',
      '# This is an autogenerated file from Tapioca.',
      '',
      'module Foo; end',
    ].join('\n')
    expectGenerated('foo.rbi', content)
  })
  it("doesn't flag plain .rbi without banner", () => {
    const content = '# typed: true\n\nmodule Foo; end\n'
    expectNotGenerated('foo.rbi', content)
  })
})

describe('classifyByContent — MySQL view definition', () => {
  it('flags .frm with TYPE=VIEW', () => {
    expectGenerated('my_view.frm', 'TYPE=VIEW\nquery=SELECT 1\n')
  })
})

describe('classifyByContent — no match', () => {
  it.each([
    ['src/App.tsx', 'import React from "react"\nexport const App = () => null\n'],
    ['cli.ts', 'import { main } from "./main.ts"\nmain()\n'],
    ['server/main.ts', 'export function startServer() {}\n'],
    ['README.md', '# Title\n\nSome content.\n'],
  ])('%s returns no attributes', (path, content) => {
    expectNotGenerated(path, content)
  })
})
