/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * Copyright Oxide Computer Company
 */

/**
 * Linguist's content-based "generated" rules — the ones that need to
 * inspect file contents (first/last lines, line counts, etc.) rather
 * than filenames.
 *
 * Ported from:
 *   github-linguist/linguist @ 537297cdae3ab05f8d5dd1c03627a5bd73707b19
 *   - lib/linguist/generated.rb
 *
 * Every rule only sets `generated` — Linguist's vendored and
 * documentation checks are path-based and live in `pathRules.ts`.
 */

import type { FileAttrs } from '../../shared/types.ts'
import type { BlobSummary } from './contentReader.ts'

export function classifyByContent(path: string, summary: BlobSummary): Partial<FileAttrs> {
  return isGenerated(path, summary) ? { generated: true } : {}
}

function isGenerated(path: string, s: BlobSummary): boolean {
  return (
    minified(path, s) ||
    hasSourceMapRef(path, s) ||
    isSourceMap(path, s) ||
    compiledCoffeescript(path, s) ||
    generatedNetDocfile(path, s) ||
    generatedParser(path, s) ||
    generatedPostscript(path, s) ||
    generatedGo(path, s) ||
    generatedProtocolBufferFromGo(path, s) ||
    generatedProtocolBuffer(path, s) ||
    generatedJavascriptProtocolBuffer(path, s) ||
    generatedTypescriptProtocolBuffer(path, s) ||
    generatedApacheThrift(path, s) ||
    generatedJniHeader(path, s) ||
    vcrCassette(path, s) ||
    generatedAntlr(path, s) ||
    compiledCythonFile(path, s) ||
    generatedModule(path, s) ||
    generatedUnity3dMeta(path, s) ||
    generatedRacc(path, s) ||
    generatedJflex(path, s) ||
    generatedGrammarkit(path, s) ||
    generatedRoxygen2(path, s) ||
    generatedJison(path, s) ||
    generatedGrpcCpp(path, s) ||
    generatedDart(path, s) ||
    generatedPerlPpportHeader(path, s) ||
    generatedGamemakerstudio(path, s) ||
    generatedGimp(path, s) ||
    generatedVisualstudio6(path, s) ||
    generatedHaxe(path, s) ||
    generatedHtml(path, s) ||
    generatedJooq(path, s) ||
    generatedSorbetRbi(path, s) ||
    generatedMysqlViewDefinitionFormat(path, s)
  )
}

// --- Path helpers ---

function extname(path: string): string {
  const slash = path.lastIndexOf('/')
  const base = slash === -1 ? path : path.slice(slash + 1)
  const dot = base.lastIndexOf('.')
  return dot === -1 ? '' : base.slice(dot)
}

function basename(path: string): string {
  const slash = path.lastIndexOf('/')
  return slash === -1 ? path : path.slice(slash + 1)
}

// --- Rule implementations (preserving Ruby source order where practical) ---

const MAYBE_MINIFIED = new Set(['.js', '.css'])

function maybeMinified(path: string): boolean {
  return MAYBE_MINIFIED.has(extname(path).toLowerCase())
}

// minified_files?
function minified(path: string, s: BlobSummary): boolean {
  if (!maybeMinified(path)) return false
  if (s.lines.length === 0) return false
  const total = s.lines.reduce((acc, l) => acc + l.length, 0)
  return total / s.lines.length > 110
}

// has_source_map?
function hasSourceMapRef(path: string, s: BlobSummary): boolean {
  if (!maybeMinified(path)) return false
  const tail = s.lines.slice(-2)
  // eslint-disable-next-line unicorn/prefer-string-starts-ends-with
  return tail.some((l) => /^\/[*/][#@] source(?:Mapping)?URL|sourceURL=/.test(l))
}

// source_map?
function isSourceMap(path: string, s: BlobSummary): boolean {
  if (extname(path).toLowerCase() !== '.map') return false
  if (/(\.css|\.js)\.map$/i.test(path)) return true
  const first = s.lines[0] ?? ''
  // eslint-disable-next-line unicorn/prefer-string-starts-ends-with
  return /^{"version":\d+,/.test(first) || first.startsWith('/** Begin line maps. **/{')
}

// compiled_coffeescript?
function compiledCoffeescript(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.js') return false
  const first = s.lines[0] ?? ''
  if (first.startsWith('// Generated by ')) return true
  if (s.lines.length < 3) return false
  if (first !== '(function() {') return false
  if (s.lines[s.lines.length - 2] !== '}).call(this);') return false
  if (s.lines[s.lines.length - 1] !== '') return false

  let score = 0
  for (const line of s.lines) {
    if (!/var /.test(line)) continue
    score += countMatches(line, /_fn|_i|_len|_ref|_results/g)
    score += 3 * countMatches(line, /__bind|__extends|__hasProp|__indexOf|__slice/g)
  }
  return score >= 3
}

function countMatches(s: string, re: RegExp): number {
  return (s.match(re) ?? []).length
}

// generated_net_docfile?
function generatedNetDocfile(path: string, s: BlobSummary): boolean {
  if (extname(path).toLowerCase() !== '.xml') return false
  if (s.lines.length <= 3) return false
  return (
    (s.lines[1]?.includes('<doc>') ?? false) &&
    (s.lines[2]?.includes('<assembly>') ?? false) &&
    (s.lines[s.lines.length - 2]?.includes('</doc>') ?? false)
  )
}

// generated_parser?  (PEG.js)
function generatedParser(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.js') return false
  const head = s.lines.slice(0, 5).join('')
  return /^(?:[^/]|\/[^*])*\/\*(?:[^*]|\*[^/])*Generated by PEG\.js/.test(head)
}

// generated_postscript?
function generatedPostscript(path: string, s: BlobSummary): boolean {
  if (!['.ps', '.eps', '.pfa'].includes(extname(path))) return false

  // Full content check for the two hex-stream markers.
  const joined = s.lines.join('\n')
  if (/^\s*(?:currentfile eexec\s+|\/sfnts\s+\[\s<)/m.test(joined)) return true

  const head = s.lines.slice(0, 10)
  const creator = head.find((l) => l.startsWith('%%Creator: '))
  if (!creator) return false

  if (
    /[0-9]|draw|mpage|ImageMagick|inkscape|MATLAB/.test(creator) ||
    /PCBNEW|pnmtops|\(Unknown\)|Serif Affinity|Filterimage -tops/.test(creator)
  ) {
    return true
  }

  // EAGLE check
  if (creator.includes('EAGLE')) {
    return s.lines.slice(0, 5).some((l) => l.startsWith('%%Title: EAGLE Drawing '))
  }
  return false
}

// generated_go?
function generatedGo(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.go') return false
  if (s.lines.length <= 1) return false
  return s.lines.slice(0, 40).some((l) => /^\/\/ Code generated .*/.test(l))
}

// generated_protocol_buffer_from_go?
function generatedProtocolBufferFromGo(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.proto') return false
  if (s.lines.length <= 1) return false
  return s.lines
    .slice(0, 20)
    .some((l) => l.includes('This file was autogenerated by go-to-protobuf'))
}

const PROTOBUF_EXTS = new Set(['.py', '.java', '.h', '.cc', '.cpp', '.m', '.rb', '.php'])

// generated_protocol_buffer?
function generatedProtocolBuffer(path: string, s: BlobSummary): boolean {
  if (!PROTOBUF_EXTS.has(extname(path))) return false
  if (s.lines.length <= 1) return false
  return s.lines
    .slice(0, 3)
    .some((l) => l.includes('Generated by the protocol buffer compiler.  DO NOT EDIT!'))
}

// generated_javascript_protocol_buffer?
function generatedJavascriptProtocolBuffer(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.js') return false
  if (s.lines.length <= 6) return false
  return s.lines[5]?.includes('GENERATED CODE -- DO NOT EDIT!') ?? false
}

// generated_typescript_protocol_buffer?
function generatedTypescriptProtocolBuffer(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.ts') return false
  if (s.lines.length <= 4) return false
  return (
    s.lines[0]?.includes('Code generated by protoc-gen-ts_proto. DO NOT EDIT.') ?? false
  )
}

const APACHE_THRIFT_EXTS = new Set([
  '.rb',
  '.py',
  '.go',
  '.js',
  '.m',
  '.java',
  '.h',
  '.cc',
  '.cpp',
  '.php',
])

// generated_apache_thrift?
function generatedApacheThrift(path: string, s: BlobSummary): boolean {
  if (!APACHE_THRIFT_EXTS.has(extname(path))) return false
  return s.lines.slice(0, 6).some((l) => l.includes('Autogenerated by Thrift Compiler'))
}

// generated_jni_header?
function generatedJniHeader(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.h') return false
  if (s.lines.length <= 2) return false
  return (
    (s.lines[0]?.includes('/* DO NOT EDIT THIS FILE - it is machine generated */') ??
      false) &&
    (s.lines[1]?.includes('#include <jni.h>') ?? false)
  )
}

// vcr_cassette?
function vcrCassette(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.yml') return false
  if (s.lines.length <= 2) return false
  return s.lines[s.lines.length - 2]?.includes('recorded_with: VCR') ?? false
}

// generated_antlr?
function generatedAntlr(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.g') return false
  if (s.lines.length <= 2) return false
  return s.lines[1]?.includes('generated by Xtest') ?? false
}

// compiled_cython_file?
function compiledCythonFile(path: string, s: BlobSummary): boolean {
  if (!['.c', '.cpp'].includes(extname(path))) return false
  if (s.lines.length <= 1) return false
  return s.lines[0]?.includes('Generated by Cython') ?? false
}

// generated_module?
function generatedModule(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.mod') return false
  if (s.lines.length <= 1) return false
  const first = s.lines[0] ?? ''
  return first.includes('PCBNEW-LibModule-V') || first.includes("GFORTRAN module version '")
}

// generated_unity3d_meta?
function generatedUnity3dMeta(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.meta') return false
  if (s.lines.length <= 1) return false
  return s.lines[0]?.includes('fileFormatVersion: ') ?? false
}

// generated_racc?
function generatedRacc(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.rb') return false
  if (s.lines.length <= 2) return false
  return s.lines[2]?.startsWith('# This file is automatically generated by Racc') ?? false
}

// generated_jflex?
function generatedJflex(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.java') return false
  if (s.lines.length <= 1) return false
  return s.lines[0]?.startsWith('/* The following code was generated by JFlex ') ?? false
}

// generated_grammarkit?
function generatedGrammarkit(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.java') return false
  if (s.lines.length <= 1) return false
  return (
    s.lines[0]?.startsWith(
      '// This is a generated file. Not intended for manual editing.',
    ) ?? false
  )
}

// generated_roxygen2?
function generatedRoxygen2(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.Rd') return false
  if (s.lines.length <= 1) return false
  return s.lines[0]?.includes('% Generated by roxygen2: do not edit by hand') ?? false
}

// generated_jison?
function generatedJison(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.js') return false
  if (s.lines.length <= 1) return false
  const first = s.lines[0] ?? ''
  return (
    first.startsWith('/* parser generated by jison ') ||
    first.startsWith('/* generated by jison-lex ')
  )
}

const GRPC_CPP_EXTS = new Set(['.cpp', '.hpp', '.h', '.cc'])

// generated_grpc_cpp?
function generatedGrpcCpp(path: string, s: BlobSummary): boolean {
  if (!GRPC_CPP_EXTS.has(extname(path))) return false
  if (s.lines.length <= 1) return false
  return s.lines[0]?.startsWith('// Generated by the gRPC') ?? false
}

// generated_dart?
function generatedDart(path: string, s: BlobSummary): boolean {
  if (extname(path) !== '.dart') return false
  if (s.lines.length <= 1) return false
  return s.lines.slice(0, 3).some((l) => /generated code\W{2,3}do not modify/i.test(l))
}

// generated_perl_ppport_header?
function generatedPerlPpportHeader(path: string, s: BlobSummary): boolean {
  if (!basename(path).endsWith('ppport.h')) return false
  if (s.lines.length <= 10) return false
  return s.lines[8]?.includes('Automatically created by Devel::PPPort') ?? false
}

// generated_gamemakerstudio?
function generatedGamemakerstudio(path: string, s: BlobSummary): boolean {
  if (!['.yy', '.yyp'].includes(extname(path))) return false
  if (s.lines.length <= 3) return false
  const joined = s.lines.slice(0, 3).join('')
  return /^\s*[{[]/.test(joined) || /^\d\.\d\.\d.+\|\{/.test(s.lines[0] ?? '')
}

// generated_gimp?
function generatedGimp(path: string, s: BlobSummary): boolean {
  if (!['.c', '.h'].includes(extname(path))) return false
  if (s.lines.length === 0) return false
  const first = s.lines[0] ?? ''
  return (
    /^\/\* GIMP [a-zA-Z0-9\- ]+ C-Source image dump \(.+?\.c\) \*\//.test(first) ||
    /^\/\*  GIMP header image file format \([a-zA-Z0-9\- ]+\): .+?\.h  \*\//.test(first)
  )
}

// generated_visualstudio6?
function generatedVisualstudio6(path: string, s: BlobSummary): boolean {
  if (extname(path).toLowerCase() !== '.dsp') return false
  return s.lines
    .slice(0, 3)
    .some((l) => l.includes('# Microsoft Developer Studio Generated Build File'))
}

const HAXE_EXTS = new Set(['.js', '.py', '.lua', '.cpp', '.h', '.java', '.cs', '.php'])

// generated_haxe?
function generatedHaxe(path: string, s: BlobSummary): boolean {
  if (!HAXE_EXTS.has(extname(path))) return false
  return s.lines.slice(0, 3).some((l) => l.includes('Generated by Haxe'))
}

// generated_html?
function generatedHtml(path: string, s: BlobSummary): boolean {
  if (!['.html', '.htm', '.xhtml'].includes(extname(path).toLowerCase())) {
    return false
  }
  if (s.lines.length <= 1) return false

  const head = s.lines.slice(0, 31)

  // pkgdown marker (first 2 lines)
  if (
    head
      .slice(0, 2)
      .some((l) => /<!-- Generated by pkgdown: do not edit by hand -->/.test(l))
  ) {
    return true
  }
  // Mandoc marker (line 2)
  if (
    s.lines.length > 2 &&
    s.lines[2]?.startsWith('<!-- This is an automatically generated file.')
  ) {
    return true
  }
  // Doxygen marker (first 31 lines)
  if (head.some((l) => /<!--\s+Generated by Doxygen\s+[.0-9]+\s*-->/i.test(l))) {
    return true
  }

  // <meta name="generator" content="..."> style
  const joined = head.join(' ')
  const metaMatches = [...joined.matchAll(/<meta(\s+[^>]+)>/gi)]
  if (metaMatches.length === 0) return false
  return metaMatches.some((m) => {
    const attrs = extractHtmlMeta(m[1] ?? '')
    if ((attrs['name'] ?? '').toLowerCase() !== 'generator') return false
    const cv = [attrs['content'], attrs['value']].filter((v): v is string => !!v)
    return cv.some((v) =>
      /^\s*(?:org\s+mode|j?latex2html|groff|makeinfo|texi2html|ronn)\b/i.test(v),
    )
  })
}

function extractHtmlMeta(attrStr: string): Record<string, string> {
  const result: Record<string, string> = {}
  const cleaned = attrStr.replace(/\/\s*$/, '').trim()
  const re = /(?<=^|\s)(name|content|value)\s*=\s*("[^"]+"|'[^']+'|[^\s"']+)/gi
  for (const m of cleaned.matchAll(re)) {
    const key = m[1]!.toLowerCase()
    let val = m[2]!
    val = val.replace(/^["']|["']$/g, '')
    result[key] = val
  }
  return result
}

// generated_jooq?
function generatedJooq(path: string, s: BlobSummary): boolean {
  if (extname(path).toLowerCase() !== '.java') return false
  return s.lines.slice(0, 2).some((l) => l.includes('This file is generated by jOOQ.'))
}

// generated_sorbet_rbi?  (Tapioca)
function generatedSorbetRbi(path: string, s: BlobSummary): boolean {
  if (extname(path).toLowerCase() !== '.rbi') return false
  if (s.lines.length < 5) return false
  if (!(s.lines[0] ?? '').startsWith('# typed:')) return false
  // Ruby's implementation checks for Tapioca's standard header in the next
  // few lines. See the source; we accept any of the three Tapioca variants.
  return s.lines
    .slice(1, 5)
    .some((l) =>
      /DO NOT EDIT MANUALLY|This is an autogenerated file|DO NOT EDIT: This file is automatically generated/i.test(
        l,
      ),
    )
}

// generated_mysql_view_definition_format?
function generatedMysqlViewDefinitionFormat(path: string, s: BlobSummary): boolean {
  if (extname(path).toLowerCase() !== '.frm') return false
  return s.lines[0]?.includes('TYPE=VIEW') ?? false
}
